// Import the UI component from the better-auth-ui library that will render the authentication forms.
import { AuthView } from "@daveyplate/better-auth-ui"
// Import the predefined paths for the authentication views (e.g., 'sign-in', 'sign-up')
// This is used for generating static pages at build time.
import { authViewPaths } from "@daveyplate/better-auth-ui/server"

// This Next.js option ensures that only the paths generated by `generateStaticParams` are allowed.
// Any other path will result in a 404 error.
export const dynamicParams = false

// This function generates the static paths for the authentication pages at build time.
// It maps over the `authViewPaths` to create a list of pages to pre-render.
// For example: /auth/sign-in, /auth/sign-up, etc.
export function generateStaticParams() {
    return Object.values(authViewPaths).map((pathname) => ({ pathname }))
}

// This is the main React Server Component for the authentication pages.
// It's a dynamic route that catches different auth paths like 'sign-in', 'sign-up', etc.
export default async function AuthPage({ params }: { params: Promise<{ pathname: string }> }) {
    // Await the params promise to resolve, then get the `pathname` property.
    // This corresponds to the dynamic segment `[pathname]` in the file path.
    const { pathname } = await params;
    
    // Renders the main content of the page, centered vertically and horizontally.
    return (
        <main className="container flex grow flex-col items-center justify-center self-center p-4 md:p-6">
            {/* The AuthView component displays the correct UI based on the path from the URL. */}
            <AuthView path={pathname} />
        </main>
    )
}
